// generated by go run gen-fonts.go; DO NOT EDIT

// Package liberationsansbold provides the "LiberationSans Bold" TrueType font
// from the Liberation font family.
package liberationsansbold // import "sdk/liberation/liberationsansbold"

import _ "embed"

// TTF is the data for the "LiberationSans Bold" TrueType font.
//
//go:embed LiberationSans-Bold.ttf
var TTF []byte
