// generated by go run gen-fonts.go; DO NOT EDIT

// Package lmmath provides the "latinmodern math" TrueType font
// from the Latin Modern font family.
package lmmath // import "sdk/latin-modern/lmmath"

import _ "embed"

// TTF is the data for the "latinmodern math" TrueType font.
//
//go:embed latinmodern-math.otf
var TTF []byte
